'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000, PASS=process.env.APP_PASSWORD||'', SECRET=process.env.SESSION_SECRET||'contas-secret';
const FILE=path.join(__dirname,'contas-data.json');
if(!fs.existsSync(FILE)) fs.writeFileSync(FILE,'[]');
function read(){try{return JSON.parse(fs.readFileSync(FILE,'utf8'))}catch{return[]}}
function write(v){fs.writeFileSync(FILE,JSON.stringify(v,null,2))}
function send(res,s,b,t='application/json; charset=utf-8',h={}){res.writeHead(s,{'Content-Type':t,'Cache-Control':'no-store',...h});res.end(typeof b==='string'?b:JSON.stringify(b))}
function body(req){return new Promise((ok,ko)=>{let d='';req.on('data',c=>d+=c);req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch{ko()}})})}
function token(){return crypto.createHmac('sha256',SECRET).update(PASS).digest('hex')}
function auth(req){if(!PASS)return true; return (req.headers.cookie||'').includes('cp='+token())}
const html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#17324d"><link rel="manifest" href="/manifest.webmanifest"><title>Contas a Pagar</title><style>
*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#f4f7fa;color:#183247}header{background:#17324d;color:white;padding:16px 20px;display:flex;justify-content:space-between;align-items:center;position:sticky;top:0}h1,h2{margin:0}.wrap{max-width:1150px;margin:auto;padding:20px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.card,.panel{background:white;border-radius:14px;padding:16px;box-shadow:0 3px 14px #0001}.card b{font-size:24px;display:block;margin-top:8px}.danger b{color:#b42318}.success b{color:#157347}.actions,.filters{display:flex;gap:10px;flex-wrap:wrap;align-items:end}.btn{border:0;border-radius:10px;padding:11px 14px;cursor:pointer;font-weight:700}.primary{background:#f28c28;color:white}.secondary{background:#e8eef3;color:#17324d}.dangerbtn{background:#fee4e2;color:#b42318}input,select,textarea{width:100%;padding:10px;border:1px solid #ccd6df;border-radius:9px;background:white}.filters label{min-width:180px;flex:1}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{text-align:left;padding:11px;border-bottom:1px solid #e7edf2}th{font-size:13px;color:#627487}.badge{padding:5px 9px;border-radius:999px;font-size:12px;font-weight:700}.pending{background:#fff3cd;color:#7a5b00}.paid{background:#d1e7dd;color:#0f5132}.overdue{background:#f8d7da;color:#842029}.login{max-width:360px;margin:12vh auto;background:white;padding:24px;border-radius:16px;box-shadow:0 6px 24px #0002}.hidden{display:none!important}dialog{border:0;border-radius:16px;width:min(700px,94vw)}dialog::backdrop{background:#0008}.form{display:grid;grid-template-columns:1fr 1fr;gap:12px}.span{grid-column:1/-1}.right{text-align:right}.small{font-size:12px;color:#667}.topbtn{background:#ffffff22;color:white}.empty{text-align:center;padding:30px;color:#667}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}.tablewrap{overflow:auto}.form{grid-template-columns:1fr}.span{grid-column:auto}}@media(max-width:500px){.grid{grid-template-columns:1fr}.wrap{padding:12px}header{padding:12px}.hide-mobile{display:none}}
</style></head><body>
<div id="login" class="login hidden"><h2>Contas a Pagar</h2><p>Digite sua senha para acessar.</p><input id="pw" type="password" placeholder="Senha"><button class="btn primary" style="width:100%;margin-top:10px" onclick="login()">Entrar</button><p id="err" style="color:#b42318"></p></div>
<div id="app" class="hidden"><header><div><b>R$ Contas a Pagar</b><div style="font-size:12px;opacity:.8">Celular e notebook</div></div><button class="btn topbtn" onclick="logout()">Sair</button></header><div class="wrap">
<div class="actions"><button class="btn primary" onclick="novo()">＋ Nova conta</button><button class="btn secondary" onclick="exportar()">Exportar CSV</button></div>
<div class="grid"><div class="card"><span>Pendente</span><b id="sPend">R$ 0,00</b><small id="cPend"></small></div><div class="card danger"><span>Vencido</span><b id="sVenc">R$ 0,00</b><small id="cVenc"></small></div><div class="card"><span>Vence no mês</span><b id="sMes">R$ 0,00</b></div><div class="card success"><span>Pago no mês</span><b id="sPago">R$ 0,00</b></div></div>
<div class="panel filters"><label>Buscar<input id="q" oninput="render()" placeholder="Descrição, fornecedor..."></label><label>Status<select id="fs" onchange="render()"><option value="all">Todos</option><option value="pending">Pendentes</option><option value="paid">Pagos</option><option value="overdue">Vencidos</option></select></label><label>Mês<input id="fm" type="month" onchange="render()"></label></div>
<div class="panel" style="margin-top:14px"><h2>Contas</h2><div class="tablewrap"><table><thead><tr><th>Vencimento</th><th>Conta</th><th>Fornecedor</th><th>Categoria</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody id="tb"></tbody></table><div id="empty" class="empty hidden">Nenhuma conta encontrada.</div></div></div>
</div></div>
<dialog id="dlg"><h2 id="dt">Nova conta</h2><div class="form" style="margin-top:14px"><label class="span">Descrição<input id="d" required></label><label>Fornecedor<input id="f"></label><label>Categoria<input id="c" value="Outros"></label><label>Valor (R$)<input id="v" type="number" step="0.01" min="0"></label><label>Vencimento<input id="dv" type="date"></label><label>Documento<input id="doc"></label><label>Status<select id="st" onchange="payFields()"><option value="pending">Pendente</option><option value="paid">Pago</option></select></label><label id="pdw" class="hidden">Data pagamento<input id="pd" type="date"></label><label id="pmw" class="hidden">Forma pagamento<select id="pm"><option value="">Selecione</option><option>PIX</option><option>Boleto</option><option>Transferência</option><option>Cartão</option><option>Dinheiro</option><option>Débito automático</option><option>Outro</option></select></label><label class="span">Observações<textarea id="n" rows="3"></textarea></label></div><div class="actions" style="margin-top:14px"><button id="del" class="btn dangerbtn hidden" onclick="excluir()">Excluir</button><span style="flex:1"></span><button class="btn secondary" onclick="dlg.close()">Cancelar</button><button class="btn primary" onclick="salvar()">Salvar</button></div><p id="ferr" style="color:#b42318"></p></dialog>
<script>
let data=[],edit=null;const $=id=>document.getElementById(id), brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});let dlg;
async function api(u,o={}){let r=await fetch(u,{headers:{'Content-Type':'application/json'},...o});if(r.status===401){showLogin();throw Error('auth')}let x=await r.json().catch(()=>({}));if(!r.ok)throw Error(x.error||'Erro');return x}
async function init(){dlg=$('dlg');let me=await fetch('/api/me').then(r=>r.json());if(!me.authenticated)return showLogin();$('login').classList.add('hidden');$('app').classList.remove('hidden');await load();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js')}
function showLogin(){$('app').classList.add('hidden');$('login').classList.remove('hidden')}
async function login(){try{await api('/api/login',{method:'POST',body:JSON.stringify({password:$('pw').value})});$('err').textContent='';init()}catch(e){$('err').textContent='Senha incorreta.'}}
async function logout(){await fetch('/api/logout',{method:'POST'});showLogin()}
async function load(){data=await api('/api/bills');render()}
function render(){let q=$('q').value.toLowerCase(),s=$('fs').value,m=$('fm').value,t=today(),cm=t.slice(0,7);let rows=data.filter(x=>(!q||[x.description,x.supplier,x.category,x.documentNumber,x.notes].some(z=>(z||'').toLowerCase().includes(q)))&&(!m||x.dueDate.startsWith(m))&&(s==='all'||(s==='overdue'?x.status==='pending'&&x.dueDate<t:x.status===s))).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));let pend=data.filter(x=>x.status==='pending'),venc=pend.filter(x=>x.dueDate<t),mes=data.filter(x=>x.dueDate.startsWith(cm)),pago=data.filter(x=>x.status==='paid'&&(x.paymentDate||'').startsWith(cm));$('sPend').textContent=brl(pend.reduce((a,x)=>a+x.amount,0));$('cPend').textContent=pend.length+' conta(s)';$('sVenc').textContent=brl(venc.reduce((a,x)=>a+x.amount,0));$('cVenc').textContent=venc.length+' conta(s)';$('sMes').textContent=brl(mes.reduce((a,x)=>a+x.amount,0));$('sPago').textContent=brl(pago.reduce((a,x)=>a+x.amount,0));$('empty').classList.toggle('hidden',rows.length>0);$('tb').innerHTML=rows.map(x=>{let ov=x.status==='pending'&&x.dueDate<t,cl=x.status==='paid'?'paid':ov?'overdue':'pending',tx=x.status==='paid'?'Pago':ov?'Vencido':'Pendente';return '<tr><td>'+fmt(x.dueDate)+'</td><td><b>'+esc(x.description)+'</b></td><td>'+esc(x.supplier||'-')+'</td><td>'+esc(x.category||'-')+'</td><td>'+brl(x.amount)+'</td><td><span class="badge '+cl+'">'+tx+'</span></td><td><button class="btn secondary" onclick="editar(\''+x.id+'\')">Editar</button>'+(x.status==='pending'?' <button class="btn primary" onclick="baixar(\''+x.id+'\')">Pagar</button>':'')+'</td></tr>'}).join('')}
function fmt(d){if(!d)return'-';let[a,m,b]=d.split('-');return b+'/'+m+'/'+a}function esc(s){return String(s||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function novo(){edit=null;$('dt').textContent='Nova conta';['d','f','doc','n','pm','pd'].forEach(i=>$(i).value='');$('c').value='Outros';$('v').value='';$('dv').value=today();$('st').value='pending';$('del').classList.add('hidden');payFields();dlg.showModal()}
function editar(id){let x=data.find(z=>z.id===id);edit=id;$('dt').textContent='Editar conta';$('d').value=x.description;$('f').value=x.supplier||'';$('c').value=x.category||'Outros';$('v').value=x.amount;$('dv').value=x.dueDate;$('doc').value=x.documentNumber||'';$('st').value=x.status;$('pd').value=x.paymentDate||'';$('pm').value=x.paymentMethod||'';$('n').value=x.notes||'';$('del').classList.remove('hidden');payFields();dlg.showModal()}
function payFields(){let on=$('st').value==='paid';$('pdw').classList.toggle('hidden',!on);$('pmw').classList.toggle('hidden',!on);if(on&&!$('pd').value)$('pd').value=today()}
async function salvar(){let o={description:$('d').value,supplier:$('f').value,category:$('c').value,amount:Number($('v').value),dueDate:$('dv').value,documentNumber:$('doc').value,status:$('st').value,paymentDate:$('pd').value,paymentMethod:$('pm').value,notes:$('n').value};try{if(!o.description||!o.dueDate||!Number.isFinite(o.amount))throw Error('Preencha descrição, valor e vencimento.');await api(edit?'/api/bills/'+edit:'/api/bills',{method:edit?'PUT':'POST',body:JSON.stringify(o)});dlg.close();await load()}catch(e){$('ferr').textContent=e.message}}
async function excluir(){if(edit&&confirm('Excluir esta conta?')){await api('/api/bills/'+edit,{method:'DELETE'});dlg.close();await load()}}
async function baixar(id){let x=data.find(z=>z.id===id);await api('/api/bills/'+id,{method:'PUT',body:JSON.stringify({...x,status:'paid',paymentDate:today()})});await load()}
function exportar(){let h=['Vencimento','Descrição','Fornecedor','Categoria','Valor','Status','Pagamento','Forma','Documento','Observações'];let r=data.map(x=>[x.dueDate,x.description,x.supplier,x.category,x.amount,x.status,x.paymentDate,x.paymentMethod,x.documentNumber,x.notes]);let csv=[h,...r].map(a=>a.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n');let b=new Blob(['\ufeff'+csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='contas-a-pagar.csv';a.click();URL.revokeObjectURL(a.href)}
init();
</script></body></html>`;
function manifest(){return JSON.stringify({name:'Contas a Pagar',short_name:'Contas',start_url:'/',display:'standalone',background_color:'#f4f7fa',theme_color:'#17324d'})}
function sw(){return `self.addEventListener('install',e=>self.skipWaiting());self.addEventListener('activate',e=>e.waitUntil(clients.claim()));`}
function norm(o,old={}){if(!o.description||!o.dueDate||!Number.isFinite(Number(o.amount))) throw Error('Dados inválidos');return {id:old.id||crypto.randomUUID(),description:String(o.description).trim(),supplier:String(o.supplier||''),category:String(o.category||'Outros'),amount:Math.round(Number(o.amount)*100)/100,dueDate:String(o.dueDate).slice(0,10),documentNumber:String(o.documentNumber||''),status:o.status==='paid'?'paid':'pending',paymentDate:o.status==='paid'?String(o.paymentDate||o.dueDate).slice(0,10):'',paymentMethod:o.status==='paid'?String(o.paymentMethod||''):'',notes:String(o.notes||''),createdAt:old.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}}
http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://x');if(u.pathname==='/manifest.webmanifest')return send(res,200,manifest(),'application/manifest+json');if(u.pathname==='/sw.js')return send(res,200,sw(),'application/javascript');if(u.pathname==='/api/me')return send(res,200,{authenticated:auth(req),authRequired:!!PASS});if(u.pathname==='/api/login'&&req.method==='POST'){let b=await body(req);if(PASS&&b.password!==PASS)return send(res,401,{error:'Senha incorreta'});return send(res,200,{ok:true},'application/json; charset=utf-8',{'Set-Cookie':'cp='+token()+'; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=2592000'})}if(u.pathname==='/api/logout'&&req.method==='POST')return send(res,200,{ok:true},'application/json; charset=utf-8',{'Set-Cookie':'cp=; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=0'});if(u.pathname.startsWith('/api/')&&!auth(req))return send(res,401,{error:'Não autorizado'});if(u.pathname==='/api/bills'&&req.method==='GET')return send(res,200,read());if(u.pathname==='/api/bills'&&req.method==='POST'){let a=read(),b=norm(await body(req));a.push(b);write(a);return send(res,201,b)}let m=u.pathname.match(/^\/api\/bills\/([\w-]+)$/);if(m&&req.method==='PUT'){let a=read(),i=a.findIndex(x=>x.id===m[1]);if(i<0)return send(res,404,{error:'Não encontrada'});a[i]=norm(await body(req),a[i]);write(a);return send(res,200,a[i])}if(m&&req.method==='DELETE'){let a=read(),n=a.filter(x=>x.id!==m[1]);write(n);return send(res,200,{ok:true})}if(u.pathname==='/health')return send(res,200,{ok:true});return send(res,200,html,'text/html; charset=utf-8')}catch(e){return send(res,400,{error:e.message||'Erro'})}}).listen(PORT,()=>console.log('Contas a Pagar online na porta '+PORT));