const http=require('http'),https=require('https'),fs=require('fs'),path=require('path');
const {URL}=require('url');
const PORT=process.env.PORT||3000;
const ID=process.env.SPREADSHEET_ID||'1miU5AW514LbRk5UsXYsVgXL1JTj_ZJgafRmBDF-tzWU';
const GIDS={lancamentos:824972758,agendamentos:1232883750,ajudantes:438556395};
const PUB=path.join(__dirname,'public');
function fetchText(url,n=0){return new Promise((ok,no)=>{if(n>5)return no(new Error('Muitos redirecionamentos'));const q=https.get(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/csv,text/plain,*/*'}},r=>{if([301,302,303,307,308].includes(r.statusCode)&&r.headers.location){r.resume();return ok(fetchText(new URL(r.headers.location,url).toString(),n+1))}let b='';r.setEncoding('utf8');r.on('data',c=>b+=c);r.on('end',()=>{if(r.statusCode<200||r.statusCode>=300)return no(new Error('Google Sheets respondeu '+r.statusCode));if(/<html|<!doctype/i.test(b.slice(0,300)))return no(new Error('Google retornou HTML em vez dos dados'));ok(b.replace(/^\uFEFF/,''))})});q.setTimeout(25000,()=>q.destroy(new Error('Tempo esgotado ao consultar Google Sheets')));q.on('error',no)})}
function csv(t){const a=[];let r=[],f='',q=false;for(let i=0;i<t.length;i++){const c=t[i];if(q){if(c==='"'&&t[i+1]==='"'){f+='"';i++}else if(c==='"')q=false;else f+=c}else{if(c==='"')q=true;else if(c===','){r.push(f);f=''}else if(c==='\n'){r.push(f.replace(/\r$/,''));a.push(r);r=[];f=''}else f+=c}}if(f.length||r.length){r.push(f.replace(/\r$/,''));a.push(r)}if(!a.length)return[];const h=a.shift().map((x,i)=>(x||('COL_'+(i+1))).trim());return a.filter(x=>x.some(v=>String(v).trim())).map(x=>Object.fromEntries(h.map((k,i)=>[k,x[i]??''])))}
async function rows(gid){let e;for(const u of [`https://docs.google.com/spreadsheets/d/${ID}/export?format=csv&gid=${gid}`,`https://docs.google.com/spreadsheets/d/${ID}/gviz/tq?tqx=out:csv&gid=${gid}`]){try{const x=csv(await fetchText(u));if(x.length)return x;e=new Error('Aba sem linhas')}catch(err){e=err}}throw e}
http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://x');if(u.pathname==='/health'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify({ok:true}))}if(u.pathname.startsWith('/api/sheet/')){const n=u.pathname.split('/').pop(),gid=GIDS[n];if(!gid){res.writeHead(404);return res.end()}try{const x=await rows(gid);res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:true,rows:x,count:x.length}))}catch(e){res.writeHead(502,{'Content-Type':'application/json'});return res.end(JSON.stringify({ok:false,error:e.message}))}}let p=u.pathname==='/'?'index.html':u.pathname.slice(1);p=path.normalize(path.join(PUB,p));if(!p.startsWith(PUB)){res.writeHead(403);return res.end()}fs.readFile(p,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}const ext=path.extname(p);res.writeHead(200,{'Content-Type':ext==='.js'?'application/javascript; charset=utf-8':'text/html; charset=utf-8','Cache-Control':'no-cache'});res.end(d)})}catch(e){res.writeHead(500);res.end(e.message)}}).listen(PORT,'0.0.0.0',()=>{console.log('CONSTRULOG em '+PORT);rows(GIDS.ajudantes).then(x=>console.log('Google Sheets OK: '+x.length+' linhas em Ajudantes')).catch(e=>console.error('Google Sheets ERRO: '+e.message))});
