const http=require('http'),https=require('https'),fs=require('fs'),path=require('path'),net=require('net'),dns=require('dns').promises;
const {URL}=require('url');
const PORT=process.env.PORT||3000;
const ID=process.env.SPREADSHEET_ID||'1miU5AW514LbRk5UsXYsVgXL1JTj_ZJgafRmBDF-tzWU';
const GIDS={lancamentos:824972758,agendamentos:1232883750,ajudantes:438556395};
const PUB=path.join(__dirname,'public');
const SSW_TOKEN_URL=process.env.SSW_TOKEN_URL||'https://ssw.inf.br/api/generateToken';
let SSW_CACHE={token:'',expires:0};
function sswConfig(){return{domain:process.env.SSW_DOMAIN||'',username:process.env.SSW_USERNAME||'',password:process.env.SSW_PASSWORD||'',cnpj:process.env.SSW_CNPJ_EDI||''}}
function sswConfigured(){const x=sswConfig();return !!(x.domain&&x.username&&x.password&&x.cnpj)}
function postJson(url,obj){return new Promise((ok,no)=>{const u=new URL(url),body=JSON.stringify(obj),q=https.request({protocol:u.protocol,hostname:u.hostname,port:u.port||443,path:u.pathname+u.search,method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body),'User-Agent':'CONSTRULOG-Dashboard/1.0'}},r=>{let b='';r.setEncoding('utf8');r.on('data',d=>b+=d);r.on('end',()=>{let j;try{j=JSON.parse(b)}catch{j={raw:b}}if(r.statusCode>=200&&r.statusCode<300)return ok({status:r.statusCode,data:j});const msg=(j&&((j.message||j.erro||j.error)))||b||('HTTP '+r.statusCode);const e=new Error(String(msg));e.status=r.statusCode;e.data=j;no(e)})});q.setTimeout(20000,()=>q.destroy(new Error('Tempo esgotado ao conectar ao SSW')));q.on('error',no);q.write(body);q.end()})}
async function getSswToken(force=false){if(!sswConfigured())throw new Error('Credenciais SSW não configuradas');if(!force&&SSW_CACHE.token&&SSW_CACHE.expires>Date.now())return SSW_CACHE.token;const x=sswConfig(),r=await postJson(SSW_TOKEN_URL,{domain:x.domain,username:x.username,password:x.password,cnpj_edi:x.cnpj}),t=r.data&&(r.data.token||r.data.access_token);if(!t||typeof t!=='string')throw new Error('SSW respondeu sem token reconhecido');SSW_CACHE={token:t,expires:Date.now()+50*60*1000};return t}
function probePort(host,port,timeout=4500){return new Promise(ok=>{const s=net.createConnection({host,port});let done=false;const end=(open,detail='')=>{if(done)return;done=true;s.destroy();ok({port,open,detail})};s.setTimeout(timeout,()=>end(false,'timeout'));s.on('connect',()=>end(true,'tcp'));s.on('error',e=>end(false,e.code||e.message))})}
async function probeBi2(){const host=process.env.BI2_HOST||'transfer.ssw.inf.br';let addresses=[];try{addresses=await dns.lookup(host,{all:true})}catch(e){return{ok:false,host,error:'DNS: '+e.message,ports:[]}}const ports=await Promise.all([21,22,990].map(p=>probePort(host,p)));return{ok:true,host,addresses:addresses.map(x=>x.address),ports}}
function fetchText(url,n=0){return new Promise((ok,no)=>{if(n>5)return no(new Error('Muitos redirecionamentos'));const q=https.get(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'text/csv,text/plain,*/*','Cache-Control':'no-cache','Pragma':'no-cache'}},r=>{if([301,302,303,307,308].includes(r.statusCode)&&r.headers.location){r.resume();return ok(fetchText(new URL(r.headers.location,url).toString(),n+1))}let b='';r.setEncoding('utf8');r.on('data',c=>b+=c);r.on('end',()=>{if(r.statusCode<200||r.statusCode>=300)return no(new Error('Google Sheets respondeu '+r.statusCode));if(/<html|<!doctype/i.test(b.slice(0,300)))return no(new Error('Google retornou HTML em vez dos dados'));ok(b.replace(/^\uFEFF/,''))})});q.setTimeout(25000,()=>q.destroy(new Error('Tempo esgotado ao consultar Google Sheets')));q.on('error',no)})}
function csv(t){const a=[];let r=[],f='',q=false;for(let i=0;i<t.length;i++){const c=t[i];if(q){if(c==='"'&&t[i+1]==='"'){f+='"';i++}else if(c==='"')q=false;else f+=c}else{if(c==='"')q=true;else if(c===','){r.push(f);f=''}else if(c==='\n'){r.push(f.replace(/\r$/,''));a.push(r);r=[];f=''}else f+=c}}if(f.length||r.length){r.push(f.replace(/\r$/,''));a.push(r)}if(!a.length)return[];const h=a.shift().map((x,i)=>(x||('COL_'+(i+1))).trim());return a.filter(x=>x.some(v=>String(v).trim())).map(x=>Object.fromEntries(h.map((k,i)=>[k,x[i]??''])))}
async function rows(gid){let e;const cb=Date.now();for(const u of [`https://docs.google.com/spreadsheets/d/${ID}/export?format=csv&gid=${gid}&cacheBust=${cb}`,`https://docs.google.com/spreadsheets/d/${ID}/gviz/tq?tqx=out:csv&gid=${gid}&cacheBust=${cb}`]){try{const x=csv(await fetchText(u));if(x.length)return x;e=new Error('Aba sem linhas')}catch(err){e=err}}throw e}
http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://x');if(u.pathname==='/health'){res.writeHead(200,{'Content-Type':'application/json'});return res.end(JSON.stringify({ok:true}))}if(u.pathname==='/api/bi2/probe'){const x=await probeBi2();res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify(x))}if(u.pathname==='/api/ssw/status'){const configured=sswConfigured();if(!configured){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:true,configured:false,connected:false,source:'google-sheets',message:'SSW aguardando credenciais'}))}try{await getSswToken(false);res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:true,configured:true,connected:true,source:'ssw',message:'SSW conectado'}))}catch(e){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:true,configured:true,connected:false,source:'google-sheets',message:'SSW configurado, mas a autenticação falhou',error:String(e.message||e)}))}}if(u.pathname.startsWith('/api/sheet/')){const n=u.pathname.split('/').pop(),gid=GIDS[n];if(!gid){res.writeHead(404);return res.end()}try{const x=await rows(gid);res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:true,rows:x,count:x.length}))}catch(e){res.writeHead(502,{'Content-Type':'application/json'});return res.end(JSON.stringify({ok:false,error:e.message}))}}let p=u.pathname==='/'?'index.html':u.pathname.slice(1);p=path.normalize(path.join(PUB,p));if(!p.startsWith(PUB)){res.writeHead(403);return res.end()}fs.readFile(p,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}const ext=path.extname(p);res.writeHead(200,{'Content-Type':ext==='.js'?'application/javascript; charset=utf-8':'text/html; charset=utf-8','Cache-Control':'no-store, no-cache, must-revalidate','Pragma':'no-cache','Expires':'0'});res.end(d)})}catch(e){res.writeHead(500);res.end(e.message)}}).listen(PORT,'0.0.0.0',()=>{console.log('CONSTRULOG em '+PORT);rows(GIDS.ajudantes).then(x=>console.log('Google Sheets OK: '+x.length+' linhas em Ajudantes')).catch(e=>console.error('Google Sheets ERRO: '+e.message))});
