import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const __filename=fileURLToPath(import.meta.url);
const __dirname=path.dirname(__filename);
const app=express();
const PORT=process.env.PORT||10000;
app.use(express.static(path.join(__dirname,'public')));
app.get('/health',(_req,res)=>res.json({ok:true}));
app.listen(PORT,'0.0.0.0',()=>console.log('Caderno de Receitas online na porta '+PORT));
