plugins { id 'com.android.application' }

android {
    namespace 'br.com.movit.rotas'
    compileSdk 35
    defaultConfig {
        applicationId 'br.com.movit.rotas.teste'
        minSdk 26
        targetSdk 35
        versionCode 15
        versionName '0.7.6-teste'
    }
    buildTypes { release { minifyEnabled false } }
}

dependencies {
}
